### ISSUE TITLE
throw new TelegramError({ error_code: 401, description: 'Bot Token is required' })

### ISSUE THREAD

**Issue by knagak** [victorakaps/Amazon-Flipkart-Price-Drop-Alert#6]
i put the bot token in .env file too bit throwinf error always 

 code: 401,
  response: { error_code: 401, description: 'Bot Token is required' },
  description: 'Bot Token is required',
  parameters: {},
  on: {}

**Comment by victorakaps** [comment]
> i put the bot token in .env file too bit throwinf error always 
> 
>  code: 401,
>   response: { error_code: 401, description: 'Bot Token is required' },
>   description: 'Bot Token is required',
>   parameters: {},
>   on: {}
Please ping me on discord(if possible) @victorakaps  I will be able to assist you better there.

**Comment by knagak** [comment]
sent request
